# Generated by Django 5.2.9 on 2025-12-15 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id_tipo_doc', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_doc', models.CharField(help_text='Nombre del tipo de documento de identidad de una persona.', max_length=100)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'db_table': 'tipo_doc',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('numero_doc', models.CharField(max_length=20, verbose_name='Documento de identidad')),
                ('nombres', models.CharField(max_length=150)),
                ('apellido_pat', models.CharField(max_length=150)),
                ('apellido_mat', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_per', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
                ('id_tipo_doc', models.ForeignKey(db_column='id_tipo_doc', on_delete=django.db.models.deletion.CASCADE, to='security.tipodoc')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(max_length=100, unique=True)),
                ('email_inst', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to='security.persona')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
