# Generated by Django 5.2.9 on 2025-12-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_doc',
            field=models.CharField(max_length=20, verbose_name='Numero de documento de identidad'),
        ),
    ]
